### ISSUE TITLE
"Error detected while processing TextChangedI Autocommands for "<buffer=4>":" ParInfer Neovim

### ISSUE THREAD

**Issue by rajcspsg** [gpanders/nvim-parinfer#15]
I'm setting up parinfer plugin for lisp development in neovim.

I've installed neovim plugin using below code -

```
use 'gpanders/nvim-parinfer'
```

And I've also setup below configuration

```
-- parinfer options
vim.cmd([[
let g:parinfer_mode = 1
let g:parinfer_force_balance = 1
let g:parinfer_filetypes = ["clojure", "schema", "lisp", "racket", "fennel"]
]])
```

Now when I edit any clojure files I get below [error](https://i.stack.imgur.com/TBdi7.png) trace - 

> Error detected while processing TextChangedI Autocommands for "<buffer=4>":
>
> E5108: Error executing lua ...e/pack/packer/start/nvim-parinfer/lua/parinfer/setup.lua:158: attempt to call a nil value
>
> stack traceback:
>
>        ...e/pack/packer/start/nvim-parinfer/lua/parinfer/setup.lua:158: in function 'invoke_parinfer'
>
>       ...e/pack/packer/start/nvim-parinfer/lua/parinfer/setup.lua:208: in function <...e/pack/packer/start/nvim-parinfer/lua/parinfer/setup.lua:199>

What is wrong with my config and how can I fix this?

**Comment by gpanders** [comment]
`1` is an invalid value for `parinfer_mode`. As mentioned in the docs, valid values are `'smart'`, `'indent'`, or `'paren'`.
